social-media:
  - service: twitter
    link: https://x.com/restorecouncil
  - service: vimeo
    link: https://vimeo.com/restorecouncil
  - service: instagram
    link: https://www.instagram.com/restorecouncil
  - service: facebook
    link: https://www.facebook.com/restorecouncil
searchgov:
  api: https://api.gsa.gov/technology/searchgov/v2/results/i14y
  endpoint: https://search.usa.gov
  affiliate: restorethegulf
  access_key: UfTjmXOSRIpVjY3yrqntqoBg0aUCckVj7FpJGfoJ8SQ=
  inline: true
  suggestions: true
subscribe: https://public.govdelivery.com/accounts/USRESTORECOUNCIL/subscriber/new
url: https://www.restorethegulf.gov
twitter: restorecouncil
dap:
  agency: GCERC
title: RestoreTheGulf.gov
footer_navigation:
  - name: Accessibility statement
    url: /policies/#accessibility-statement
  - name: Council Member Resources
    url: /members/
  - name: Freedom of Information Act (FOIA)
    url: /policies/#freedom-of-information-act-foia
  - name: Equal employment
    url: /policies/#equal-employment
  - name: External links
    url: /policies/#external-links
  - name: Privacy policy
    url: /policies/#privacy-policy
  - name: Vulnerability disclosure policy
    url: /policies/#vulnerability-disclosure-policy
  - name: Have a question about government services? Contact USA.gov.
    url: https://usa.gov/
modify: https://public.govdelivery.com/accounts/USRESTORECOUNCIL/subscriber/new
alert:
  enabled: true
  heading: RESTORE Council Approves $403 Million for Gulf Coast Ecosystem
    Restoration in Milestone 2026 Funded Priorities List
  text: Review 2026 FPL and Response to Public Comment <a
    href="our-work/fpl/2026/">Learn More</a>
email: RestoreCouncil@restorethegulf.gov
description: The Gulf Coast Ecosystem Restoration Council (RESTORE Council) is a
  small federal agency established in the wake of the Deepwater Horizon disaster
  to plan for and carry out restoration across the Gulf Coast.
secondary_navigation:
  - name: Contact us
    url: /contact/
